# Generated by Django 4.1.5 on 2023-09-09 23:50

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import selectr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('recipe', models.URLField(max_length=500, validators=[selectr.models.validate_allrecipes])),
                ('ingres', models.JSONField(default=dict)),
                ('instruct', models.JSONField(default=dict)),
                ('image', models.URLField(max_length=500)),
                ('colour', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
