# Generated by Django 4.1.5 on 2023-06-07 18:35

from django.db import migrations, models
import selectr.models


class Migration(migrations.Migration):

    dependencies = [
        ('selectr', '0003_recipe_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.URLField(validators=[selectr.models.validate_allrecipes]),
        ),
    ]
