# Generated by Django 4.1.5 on 2023-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectr', '0004_alter_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingres',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruct',
            field=models.JSONField(default=dict),
        ),
    ]
