# Generated by Django 4.1.5 on 2023-09-09 23:50

from django.db import migrations, models
import selectr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('recipe', models.URLField(max_length=500, validators=[selectr.models.validate_allrecipes])),
                ('ingres', models.JSONField(default=dict)),
                ('instruct', models.JSONField(default=dict)),
                ('image', models.URLField(max_length=500)),
            ],
        ),
    ]
