# Generated by Django 4.1.5 on 2023-06-07 18:35

from django.db import migrations, models
import selectr.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/007/746/181/original/red-and-white-checkered-for-picnic-blanket-or-tablecloth-gingham-seamless-pattern-fabric-geometric-background-plaid-paper-retro-textile-or-texture-italian-style-flat-design-illustration-free-vector.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.URLField(validators=[selectr.models.validate_allrecipes]),
        ),
    ]
